backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - &ref_0
        label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - name: description
    label: Descriptions
    folder: cms/description
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Mission
        name: body
        widget: markdown
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: description
      - label: Layout
        widget: hidden
        name: layout
        default: '[description].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: paintings
    label: Paintings
    folder: cms/paintings
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Title
        name: body
        widget: markdown
        required: false
      - hint: ''
        name: f_hero
        label: Hero
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_dimensions
        label: Dimensions
        widget: string
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: paintings
      - label: Layout
        widget: hidden
        name: layout
        default: '[paintings].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Texts
        name: texts
        file: cms/_data/texts.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Texts
          - hint: 'Original text: Molly Pfohl Rand, key: -5c00b38f'
            label: Text
            name: '-5c00b38f'
            widget: string
          - hint: 'Original text: art consultant, key: -257887a8'
            label: Text
            name: '-257887a8'
            widget: string
          - hint: 'Original text: mollyprand@gmail.com, key: -2ac71eb1'
            label: Text
            name: '-2ac71eb1'
            widget: string
          - hint: 'Original text: 917 744-4228, key: -59e394c5'
            label: Text
            name: '-59e394c5'
            widget: string
          - hint: 'Original text: 234 Fifth Avenue, Suite 316, key: -5af07788'
            label: Text
            name: '-5af07788'
            widget: string
          - hint: 'Original text: New York NY 10001, key: 9bbe38e'
            label: Text
            name: 9bbe38e
            widget: string
          - hint: 'Original text: the art committee, key: 54341091'
            label: Text
            name: '54341091'
            widget: string
          - hint: 'Original text: instagram, key: 1b907b2'
            label: Text
            name: 1b907b2
            widget: string
          - hint: 'Original text: No items found., key: 3d503d2b'
            label: Text
            name: 3d503d2b
            widget: string
          - hint: 'Original text: Projects, key: -37ac8366'
            label: Text
            name: '-37ac8366'
            widget: string
          - hint: 'Original text: Stay in Touch, key: -336201d5'
            label: Text
            name: '-336201d5'
            widget: string
          - hint: >-
              Original text: Thank you! Your submission has been received!, key:
              5a0ea5a1
            label: Text
            name: 5a0ea5a1
            widget: string
          - hint: >-
              Original text: Oops! Something went wrong while submitting the
              form., key: -7c112e99
            label: Text
            name: '-7c112e99'
            widget: string
          - hint: 'Original text: ‍, key: 200d'
            label: Text
            name: 200d
            widget: string
          - hint: |-
              Original text: New York NY 10001
                              , key: -41a749c4
            label: Text
            name: '-41a749c4'
            widget: string
          - hint: 'Original text: Corporate commissions, key: -74764a73'
            label: Text
            name: '-74764a73'
            widget: string
          - hint: 'Original text: What’s a Rich Text element?, key: -3c0dda4d'
            label: Text
            name: '-3c0dda4d'
            widget: string
          - hint: >-
              Original text: The rich text element allows you to create and
              format headings, paragraphs, blockquotes, images, and video all in
              one place instead of having to add and format them individually.
              Just double-click and easily create content., key: 2e633c6a
            label: Text
            name: 2e633c6a
            widget: text
          - hint: 'Original text: Static and dynamic content editing, key: 57fa6135'
            label: Text
            name: 57fa6135
            widget: string
          - hint: >-
              Original text: A rich text element can be used with static or
              dynamic content. For static content, just drop it into any page
              and begin editing. For dynamic content, add a rich text field to
              any collection and then connect a rich text element to that field
              in the settings panel. Voila!, key: -a016b40
            label: Text
            name: '-a016b40'
            widget: text
          - hint: >-
              Original text: How to customize formatting for each rich text,
              key: -4bffb26e
            label: Text
            name: '-4bffb26e'
            widget: string
          - hint: >-
              Original text: Headings, paragraphs, blockquotes, figures, images,
              and figure captions can all be styled after a class is added to
              the rich text element using the "When inside of" nested selector
              system., key: -43ba1153
            label: Text
            name: '-43ba1153'
            widget: text
          - hint: 'Original text: Heading, key: -6d5fea1e'
            label: Text
            name: '-6d5fea1e'
            widget: string
      - label: Links
        name: links
        file: cms/_data/links.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Links
          - hint: 'Original link: mailto:mollyprand@gmail.com, key: 45aa5957'
            label: Link
            name: 45aa5957
            widget: string
          - hint: 'Original link: tel:917-579-6515, key: 1f99246'
            label: Link
            name: 1f99246
            widget: string
          - hint: 'Original link: https://theartcommittee.com/, key: -44aa9b40'
            label: Link
            name: '-44aa9b40'
            widget: string
          - hint: 'Original link: https://www.instagram.com/mrandart/, key: -3ba14c92'
            label: Link
            name: '-3ba14c92'
            widget: string
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: 57c1626b
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 6a0b914a
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 1764d28d
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 201c218d
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-26d42ff1'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '40195967'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-788d5a9c'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 4d08ecd2
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-269bd1ed'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 1fd5ac08
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 200e0a0c
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 2038508f
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 1ff1db0a
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
publish_mode: editorial_workflow
